### ISSUE TITLE
Don't publishSigned meta "all" project

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh-scala#11]
Currently this makes `./sbt +publishSigned` fail halfway with:
```
java.lang.RuntimeException: Repository for publishing is not specified.
	at scala.sys.package$.error(package.scala:27)
	at sbt.Classpaths$$anonfun$getPublishTo$1.apply(Defaults.scala:1411)
	at sbt.Classpaths$$anonfun$getPublishTo$1.apply(Defaults.scala:1411)
	at scala.Option.getOrElse(Option.scala:120)
	at sbt.Classpaths$.getPublishTo(Defaults.scala:1411)
	at com.typesafe.sbt.pgp.PgpSettings$$anonfun$signingSettings$2.apply(PgpSettings.scala:125)
	at com.typesafe.sbt.pgp.PgpSettings$$anonfun$signingSettings$2.apply(PgpSettings.scala:124)
	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:35)
	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (all/*:publishSignedConfiguration) Repository for publishing is not specified.
```

**Comment by mattpap** [comment]
Fixed in 1de553f by switching to sbt-pgp 1.0 and disabling SbtPgp auto-plugin for `all`.
